version: '3.7'
services:
  frontend-proxy:
    image: nicholascarr/driver-status-nginx
    ports:
     - "80:80"
  node:
    image: nicholascarr/driver-status-server
    environment:
     - NODE_ENV=production
    secrets:
     - vapid
  mongo:
    image: mongo:4.0
    volumes:
      - mongodata:/data/mongo
  redis:
    image: redis:5.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
volumes:
  mongodata:
  redisdata:
secrets:
  vapid:
    external: true